# Generated by Django 3.1.4 on 2024-05-01 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20240128_1531'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rin',
            fields=[
                ('producto_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.producto')),
                ('marca', models.CharField(default='', max_length=50)),
                ('material', models.CharField(default='', max_length=50)),
                ('tamano', models.CharField(default='', max_length=50)),
                ('fecha_fabricacion', models.DateField(blank=True, null=True)),
            ],
            bases=('core.producto',),
        ),
    ]
